spring.application.name=spring-security

# spring.security.user.name=nayak19
# spring.security.user.password=dummy

spring.devtools.restart.enabled=true
logging.level.org.springframework.boot.devtools=TRACE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb