spring.application.name=spring-security

spring.security.user.name=nayak19
spring.security.user.password=dummy

spring.devtools.restart.enabled=true
logging.level.org.springframework.boot.devtools=TRACE
