spring.application.name=oauth
spring.security.oauth2.client.registration.google.client-id=613142420712-ckub20qnjq04aub128t46504cdfddcrs.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# logging.level.org.springframework.security=TRACE
# logging.level.org.springframework.web=DEBUG
